version: '3.8'
services:
  api:
    image: parking-api
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"
  redis-server:
    networks:
      - backend
    image: 'redis'
      
networks:
  backend:
    driver: bridge